language: bash

env:
  # - N='apt-get update'      S=1 C=ssh_config H=buildbot@chrome-build1
  # - N='install python'      S=2 C=ssh_config H=buildbot@chrome-build1
  # - N='install font'        S=3 C=ssh_config H=buildbot@chrome-build1
  # - N='install depot_tools' S=4 C=ssh_config H=buildbot@chrome-build1
  # - N='fetch chromium'      S=5 C=ssh_config H=buildbot@chrome-build1 T=travis_wait W=100
  # - N='install build deps'  S=6 C=ssh_config H=buildbot@chrome-build1
  # - N='gclient sync'        S=7 C=ssh_config H=buildbot@chrome-build1 T=travis_wait W=100
  - N='git fetch'           S=8 C=ssh_config H=buildbot@chrome-build1
  - N='git checkout TARGET' S=9 C=ssh_config H=buildbot@chrome-build1
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=1
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=2
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=3
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=4
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=5
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=6
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=7
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=8
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=9
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=10
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=11
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=12
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=13
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=14
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=15
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=16
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=17
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=18
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=19
  - N='ninja'               S=10 C=ssh_config H=buildbot@chrome-build1 A=20
  - N='docker'              S=11 C=ssh_config H=buildbot@chrome-build1
before_install:
- umask 0077
- openssl aes-256-cbc -K $encrypted_d16b55db407f_key -iv $encrypted_d16b55db407f_iv
  -in ssh_config.tar.enc -out ssh_config.tar -d
- tar xvf ssh_config.tar
- rm ssh_config.tar

script: $T $W ./travis.sh $S $C $H "$TRAVIS_BUILD_NUMBER.$TRAVIS_BUILD_ID"
