language: bash
before_install:
- umask 0077
- openssl aes-256-cbc -K $encrypted_d16b55db407f_key -iv $encrypted_d16b55db407f_iv
  -in ssh_config.tar.enc -out ssh_config.tar -d
- tar xvf ssh_config.tar
- rm ssh_config.tar
- echo 'sudo apt-get -y update' | ssh -T -F ssh_config chrome-build1
# install python
- echo 'sudo apt-get -y install git python' | ssh -T -F ssh_config chrome-build1
# install mscorefont
- echo 'echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections && sudo apt-get install -y ttf-mscorefonts-installer' | ssh -T -F ssh_config chrome-build1
# TODO - install docker
# TODO - set path
#    export PATH="$PATH:/path/to/depot_tools"
# depot_tools
- echo 'git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git; cd depot_tools; git pull' | ssh -T -F ssh_config buildbot@chrome-build1

install:
# Get the sources
- echo 'mkdir -p ~/chromium && cd ~/chromium; fetch --nohooks chromium' | ssh -T -F ssh_config buildbot@chrome-build1 
