language: bash
before_install:
- umask 0077
- openssl aes-256-cbc -K $encrypted_d16b55db407f_key -iv $encrypted_d16b55db407f_iv
  -in ssh_config.tar.enc -out ssh_config.tar -d
- tar xvf ssh_config.tar
- rm ssh_config.tar

install:
- ssh -F ssh_config chrome-build1 sudo apt-get -y update
- ssh -F ssh_config chrome-build1 sudo apt-get -y install git python
